SET IDENTITY_INSERT [dbo].[vornamen] ON
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (1, N'Hannes')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (2, N'Franz')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (3, N'Maria')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (4, N'Sepp')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (5, N'Beat')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (6, N'Anne')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (7, N'Alina')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (8, N'Bea')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (9, N'Sebastian')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (10, N'Julia')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (11, N'Max')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (12, N'Davisd')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (13, N'Fabian')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (14, N'Kerstin')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (15, N'Barabra')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (16, N'Sabine')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (17, N'Jessica')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (18, N'Marlene')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (19, N'Eduard')
INSERT INTO [dbo].[vornamen] ([Id], [vorname]) VALUES (20, N'Victor')
SET IDENTITY_INSERT [dbo].[vornamen] OFF
